version: '3.10'

volumes:
  trello-case-postgres: {}

services:
  trello-case:
    container_name: trello-case
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: /start-sh

  postgres:
    image: postgres:14
    container_name: trello-case-postgres
    volumes:
      - trello-case-postgres:/var/lib/postgresql/data:Z
    env_file:
      - .env
    ports:
      - "6432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'

  celery_worker:
    image: trello-case-celery-worker
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres